pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io

// The keybind list, for the help modal.
//
// Generated by Nix from modules/desktop/hyprland/keybinds.nix, which is the same
// list that produces the actual hl.bind() calls. That is the whole point: a
// cheatsheet maintained separately from the binds it documents is wrong within a
// week, and this one is read from across a room precisely when you have
// forgotten everything.
//
// Read from /etc rather than the config dir because it describes the compositor,
// not the shell — it is true for whoever is logged in, and it is not something a
// user edits.
//
// Panel keys are the exception and are declared below. They are handled inside
// QML, by whichever panel has focus, so Nix never sees them and they cannot come
// from that file. They are still keys someone has to remember, which is the only
// thing the modal is for — a cheatsheet that documents half the bindings is
// worse than one that admits where they come from.

Singleton {
    id: root

    readonly property string path: "/etc/grootshell/keybinds.json"

    property var binds: []
    readonly property bool available: binds.length > 0

    // Handled by panels rather than by the compositor. Kept next to nothing that
    // enforces them, which is a real weakness: change a key in Island.qml,
    // Agenda.qml or Media.qml and this has to change with it. The alternative
    // was leaving them undocumented, which is worse.
    readonly property var panelBinds: [
        {
            category: "Dashboard panel",
            keys: ["Tab"],
            description: "Next tab"
        },
        {
            category: "Dashboard panel",
            keys: ["SHIFT + Tab"],
            description: "Previous tab"
        },
        {
            category: "Dashboard panel",
            // One cap rather than four keys: the modal renders extras as
            // "or X", which reads as alternatives for the same action instead
            // of a range where each key means something different.
            keys: ["1 – 5"],
            description: "Jump to Dashboard, Media, Performance, Wallpaper or Weather"
        },
        {
            category: "Dashboard panel",
            keys: ["Escape"],
            description: "Close"
        },
        {
            category: "Agenda",
            keys: ["Up", "Down"],
            description: "Move through the agenda"
        },
        {
            category: "Agenda",
            keys: ["Enter", "Space"],
            description: "Open the entry, or join its first call"
        },
        {
            category: "Agenda",
            keys: ["1 – 9"],
            description: "Join a specific call, when an entry has several"
        },
        {
            category: "Agenda",
            keys: ["Backspace"],
            description: "Back to the list"
        },
        {
            category: "Media",
            keys: ["Space", "Enter"],
            description: "Play or pause, or start the default player"
        },
        {
            category: "Media",
            keys: ["N"],
            description: "Next track"
        },
        {
            category: "Media",
            keys: ["P"],
            description: "Previous track"
        },
        {
            category: "Desktop switcher",
            keys: ["SUPER + Tab"],
            description: "Next desktop — hold SUPER and keep tapping"
        },
        {
            category: "Desktop switcher",
            keys: ["Arrows"],
            description: "Move the selection"
        },
        {
            category: "Desktop switcher",
            keys: ["Enter", "Space"],
            description: "Go there now, without waiting"
        },
        {
            category: "Desktop switcher",
            keys: ["1 – 5"],
            description: "Jump straight to a desktop"
        },
        {
            category: "Desktop switcher",
            keys: ["Escape"],
            description: "Stay where you are"
        },
        {
            category: "Wallpaper",
            keys: ["Arrows"],
            description: "Move through the grid — applies after a short pause"
        },
        {
            category: "Wallpaper",
            keys: ["Enter", "Space"],
            description: "Apply now, without waiting"
        },
        {
            category: "Wallpaper",
            keys: ["Home", "End"],
            description: "First or last wallpaper"
        },
        {
            category: "Wallpaper",
            keys: ["M"],
            description: "Cycle the light/dark override"
        }
    ]

    // Grouped for display, preserving the order categories first appear in the
    // source rather than sorting them alphabetically — the Nix list is already
    // ordered by importance, with the escape hatches first.
    readonly property var groups: {
        const order = [];
        const byCategory = {};

        // Compositor binds first: those are the ones that work when the shell
        // is dead, and the ones worth finding at the top of the sheet.
        for (const bind of root.binds.concat(root.panelBinds)) {
            const category = bind.category ?? "Other";
            if (!byCategory[category]) {
                byCategory[category] = [];
                order.push(category);
            }
            byCategory[category].push(bind);
        }

        return order.map(name => ({
                    name,
                    binds: byCategory[name]
                }));
    }

    FileView {
        path: root.path
        watchChanges: true
        blockLoading: false
        onFileChanged: reload()

        onLoaded: {
            try {
                root.binds = JSON.parse(text());
            } catch (e) {
                console.warn("grootshell: keybinds.json is not valid JSON:", e);
                root.binds = [];
            }
        }

        // Absent is the normal case for a bare dev checkout with no NixOS
        // module behind it, so this is a note rather than a warning.
        onLoadFailed: {
            console.log("grootshell: no keybind list at", root.path);
            root.binds = [];
        }
    }

    // "SUPER + SHIFT + V" -> ["SUPER", "SHIFT", "V"], for rendering each key as
    // its own cap rather than as one run-on string.
    function keys(bind): var {
        const primary = (bind.keys ?? [])[0] ?? "";
        return primary.split("+").map(k => k.trim()).filter(k => k !== "");
    }

    // Any additional bindings for the same action, shown as "or ..." so the
    // media keys do not each take a row of their own.
    function alternates(bind): var {
        return (bind.keys ?? []).slice(1);
    }
}
