pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io
import qs.config

// The keybind list, for the help modal.
//
// Generated by Nix from modules/desktop/hyprland/keybinds.nix, which is the same
// list that produces the actual hl.bind() calls. That is the whole point: a
// cheatsheet maintained separately from the binds it documents is wrong within a
// week, and this one is read from across a room precisely when you have
// forgotten everything.
//
// Read from /etc first because there it describes the compositor, not the shell
// — it is true for whoever is logged in, and is not something a user edits. The
// config directory is the fallback, for anyone who configures Hyprland
// themselves and has nowhere else to tell the shell what they chose.
//
// Panel keys are the exception and are declared below. They are handled inside
// QML, by whichever panel has focus, so Nix never sees them and they cannot come
// from that file. They are still keys someone has to remember, which is the only
// thing the modal is for — a cheatsheet that documents half the bindings is
// worse than one that admits where they come from.

Singleton {
    id: root

    // Two places, tried in order.
    //
    // /etc is where the NixOS module writes it, because there the list describes
    // the COMPOSITOR — it is true for whoever logs in, and is not something a
    // user edits. That is the right home when something else owns the binds.
    //
    // The config directory is for everyone else. Without it the cheatsheet is a
    // feature only this machine has: anyone else configures Hyprland themselves
    // and has nowhere to tell the shell what they chose.
    readonly property var sources: [
        "/etc/grootshell/keybinds.json",
        `${Config.configDir}/keybinds.json`
    ]

    property int source: 0
    readonly property string path: root.sources[root.source] ?? ""

    property var binds: []
    readonly property bool available: binds.length > 0

    // Handled by panels rather than by the compositor. Kept next to nothing that
    // enforces them, which is a real weakness: change a key in Island.qml,
    // Agenda.qml or Media.qml and this has to change with it. The alternative
    // was leaving them undocumented, which is worse.
    readonly property var panelBinds: [
        {
            category: "Dashboard panel",
            keys: ["Tab"],
            description: "Next tab"
        },
        {
            category: "Dashboard panel",
            keys: ["SHIFT + Tab"],
            description: "Previous tab"
        },
        {
            category: "Dashboard panel",
            // One cap rather than four keys: the modal renders extras as
            // "or X", which reads as alternatives for the same action instead
            // of a range where each key means something different.
            keys: ["1 – 5"],
            description: "Jump to Dashboard, Media, Performance, Wallpaper or Weather"
        },
        {
            category: "Dashboard panel",
            keys: ["Escape"],
            description: "Close"
        },
        {
            category: "Agenda",
            keys: ["Up", "Down"],
            description: "Move through the agenda"
        },
        {
            category: "Agenda",
            keys: ["Enter", "Space"],
            description: "Open the entry, or join its first call"
        },
        {
            category: "Agenda",
            keys: ["1 – 9"],
            description: "Join a specific call, when an entry has several"
        },
        {
            category: "Agenda",
            keys: ["Backspace"],
            description: "Back to the list"
        },
        {
            category: "Media",
            keys: ["Space", "Enter"],
            description: "Play or pause, or start the default player"
        },
        {
            category: "Media",
            keys: ["N"],
            description: "Next track"
        },
        {
            category: "Media",
            keys: ["P"],
            description: "Previous track"
        },
        {
            category: "Desktop switcher",
            keys: ["SUPER + Tab"],
            description: "Next desktop — hold SUPER and keep tapping"
        },
        {
            category: "Desktop switcher",
            keys: ["Arrows"],
            description: "Move the selection"
        },
        {
            category: "Desktop switcher",
            keys: ["Enter", "Space"],
            description: "Go there now, without waiting"
        },
        {
            category: "Desktop switcher",
            keys: ["1 – 5"],
            description: "Jump straight to a desktop"
        },
        {
            category: "Desktop switcher",
            keys: ["Escape"],
            description: "Stay where you are"
        },
        {
            category: "Settings",
            keys: ["Escape"],
            description: "Close — changes are written as you make them"
        },
        {
            category: "Wallpaper",
            keys: ["Arrows"],
            description: "Move through the grid — applies after a short pause"
        },
        {
            category: "Wallpaper",
            keys: ["Enter", "Space"],
            description: "Apply now, without waiting"
        },
        {
            category: "Wallpaper",
            keys: ["Home", "End"],
            description: "First or last wallpaper"
        },
        {
            category: "Wallpaper",
            keys: ["M"],
            description: "Cycle the light/dark override"
        }
    ]

    // Grouped for display, preserving the order categories first appear in the
    // source rather than sorting them alphabetically — the Nix list is already
    // ordered by importance, with the escape hatches first.
    readonly property var groups: {
        const order = [];
        const byCategory = {};

        // Compositor binds first: those are the ones that work when the shell
        // is dead, and the ones worth finding at the top of the sheet.
        for (const bind of root.binds.concat(root.panelBinds)) {
            const category = bind.category ?? "Other";
            if (!byCategory[category]) {
                byCategory[category] = [];
                order.push(category);
            }
            byCategory[category].push(bind);
        }

        return order.map(name => ({
                    name,
                    binds: byCategory[name]
                }));
    }

    // Advancing to the next source, deferred.
    //
    // Reassigning `path` from inside the FileView's own onLoadFailed does not
    // start a new load — the view is mid-failure and the change is swallowed, so
    // the path updates and nothing is ever read from it. Doing it on the next
    // turn of the event loop, and asking for the reload explicitly, is what
    // makes the fallback actually fall back.
    function advance(): void {
        if (root.source + 1 >= root.sources.length) {
            console.log("grootshell: no keybind list found; tried", root.sources.join(", "));
            return;
        }
        root.source++;
        file.reload();
    }

    FileView {
        id: file

        path: root.path
        watchChanges: true
        blockLoading: false
        onFileChanged: reload()

        onLoaded: {
            try {
                root.binds = JSON.parse(text());
            } catch (e) {
                console.warn("grootshell: keybinds.json is not valid JSON:", e);
                root.binds = [];
            }
        }

        // Absent is the normal case — /etc holds one only where the NixOS
        // module wrote it — so this falls through to the next source rather
        // than treating it as an error. Running out of sources is still not a
        // warning: a shell with no cheatsheet works fine, it just cannot tell
        // you what the compositor's keys do.
        onLoadFailed: {
            root.binds = [];
            Qt.callLater(root.advance);
        }
    }

    // "SUPER + SHIFT + V" -> ["SUPER", "SHIFT", "V"], for rendering each key as
    // its own cap rather than as one run-on string.
    function keys(bind): var {
        const primary = (bind.keys ?? [])[0] ?? "";
        return primary.split("+").map(k => k.trim()).filter(k => k !== "");
    }

    // Any additional bindings for the same action, shown as "or ..." so the
    // media keys do not each take a row of their own.
    function alternates(bind): var {
        return (bind.keys ?? []).slice(1);
    }
}
