pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io

// The keybind list, for the help modal.
//
// Generated by Nix from modules/desktop/hyprland/keybinds.nix, which is the same
// list that produces the actual hl.bind() calls. That is the whole point: a
// cheatsheet maintained separately from the binds it documents is wrong within a
// week, and this one is read from across a room precisely when you have
// forgotten everything.
//
// Read from /etc rather than the config dir because it describes the compositor,
// not the shell — it is true for whoever is logged in, and it is not something a
// user edits.

Singleton {
    id: root

    readonly property string path: "/etc/grootshell/keybinds.json"

    property var binds: []
    readonly property bool available: binds.length > 0

    // Grouped for display, preserving the order categories first appear in the
    // source rather than sorting them alphabetically — the Nix list is already
    // ordered by importance, with the escape hatches first.
    readonly property var groups: {
        const order = [];
        const byCategory = {};

        for (const bind of root.binds) {
            const category = bind.category ?? "Other";
            if (!byCategory[category]) {
                byCategory[category] = [];
                order.push(category);
            }
            byCategory[category].push(bind);
        }

        return order.map(name => ({
                    name,
                    binds: byCategory[name]
                }));
    }

    FileView {
        path: root.path
        watchChanges: true
        blockLoading: false
        onFileChanged: reload()

        onLoaded: {
            try {
                root.binds = JSON.parse(text());
            } catch (e) {
                console.warn("grootshell: keybinds.json is not valid JSON:", e);
                root.binds = [];
            }
        }

        // Absent is the normal case for a bare dev checkout with no NixOS
        // module behind it, so this is a note rather than a warning.
        onLoadFailed: {
            console.log("grootshell: no keybind list at", root.path);
            root.binds = [];
        }
    }

    // "SUPER + SHIFT + V" -> ["SUPER", "SHIFT", "V"], for rendering each key as
    // its own cap rather than as one run-on string.
    function keys(bind): var {
        const primary = (bind.keys ?? [])[0] ?? "";
        return primary.split("+").map(k => k.trim()).filter(k => k !== "");
    }

    // Any additional bindings for the same action, shown as "or ..." so the
    // media keys do not each take a row of their own.
    function alternates(bind): var {
        return (bind.keys ?? []).slice(1);
    }
}
