-- Generated by matugen from the current wallpaper. Do not edit.
return {
  foreground = "{{colors.on_surface.default.hex}}",
  background = "{{colors.background.default.hex}}",

  cursor_bg = "{{colors.primary.default.hex}}",
  cursor_fg = "{{colors.on_primary.default.hex}}",
  cursor_border = "{{colors.primary.default.hex}}",

  selection_bg = "{{colors.primary_container.default.hex}}",
  selection_fg = "{{colors.on_primary_container.default.hex}}",

  split = "{{colors.outline_variant.default.hex}}",

  -- black, red, green, yellow, blue, magenta, cyan, white
  ansi = {
    "{{colors.surface_container_highest.default.hex}}",
    "#e06c75",
    "#98c379",
    "#e5c07b",
    "#61afef",
    "#c678dd",
    "#56b6c2",
    "{{colors.on_surface_variant.default.hex}}",
  },
  brights = {
    "{{colors.outline.default.hex}}",
    "#ff7b86",
    "#a9d5a0",
    "#e8c98a",
    "#7cc4ff",
    "#d79bec",
    "#6fd3de",
    "{{colors.on_surface.default.hex}}",
  },
}
